"use client";

import { Order, Customer } from "@/lib/types/schema";
import { format } from "date-fns";

interface DocumentEngineProps {
  order: Order;
  customer?: Customer; // For Sales
  supplier?: Customer; // For Purchases (using Customer schema for now)
  type: "quote" | "invoice" | "purchase_order";
}

export function DocumentEngine({ order, customer, supplier, type }: DocumentEngineProps) {
  const entity = customer || supplier;
  const docTitle = type === "quote" ? "Sales Quote" : type === "invoice" ? "Tax Invoice" : "Purchase Order";

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="bg-white text-black p-8 max-w-[210mm] mx-auto min-h-[297mm] shadow-lg print:shadow-none print:p-0">
      {/* Print Controls - Hidden when actually printing */}
      <div className="mb-8 flex justify-end print:hidden">
        <button 
          onClick={handlePrint}
          className="bg-black text-white px-4 py-2 text-sm font-medium hover:bg-black/80 transition-colors"
        >
          Print / Save PDF
        </button>
      </div>

      {/* Header */}
      <div className="flex justify-between items-start border-b-2 border-black pb-6 mb-8">
        <div>
          <div className="size-12 bg-black text-white flex items-center justify-center font-bold text-2xl mb-4">
            S
          </div>
          <h1 className="text-2xl font-bold tracking-tight">Synocre Connect</h1>
          <p className="text-sm text-gray-600">123 Enterprise Way, Tech District</p>
          <p className="text-sm text-gray-600">contact@synocre.com</p>
        </div>
        <div className="text-right">
          <h2 className="text-4xl font-bold uppercase tracking-widest">{docTitle}</h2>
          <p className="text-sm font-semibold mt-2">Document #: {order.id.slice(0,8).toUpperCase()}</p>
          <p className="text-sm">Date: {format(new Date(order.createdAt), 'PPP')}</p>
        </div>
      </div>

      {/* Bill To / Ship To */}
      <div className="mb-12">
        <h3 className="font-bold border-b border-black inline-block mb-2 uppercase text-sm">
          {type === "purchase_order" ? "Vendor Details" : "Bill To"}
        </h3>
        {entity ? (
          <div className="text-sm space-y-1">
            <p className="font-semibold text-lg">{entity.name}</p>
            <p>{entity.industry}</p>
            <p>{entity.email}</p>
            <p>{entity.phone}</p>
          </div>
        ) : (
          <p className="text-sm text-gray-500 italic">No details provided.</p>
        )}
      </div>

      {/* Line Items */}
      <table className="w-full text-sm mb-12 border-collapse">
        <thead>
          <tr className="border-b-2 border-black">
            <th className="text-left py-2 font-bold">Item ID</th>
            <th className="text-center py-2 font-bold">Qty</th>
            <th className="text-right py-2 font-bold">Unit Price</th>
            <th className="text-right py-2 font-bold">Total</th>
          </tr>
        </thead>
        <tbody>
          {order.items.map((item, index) => (
            <tr key={index} className="border-b border-gray-200">
              <td className="py-3 font-mono text-xs">{item.productId}</td>
              <td className="py-3 text-center">{item.quantity}</td>
              <td className="py-3 text-right">${Number(item.unitPrice).toFixed(2)}</td>
              <td className="py-3 text-right font-semibold">${Number(item.totalPrice).toFixed(2)}</td>
            </tr>
          ))}
        </tbody>
      </table>

      {/* Totals */}
      <div className="flex justify-end mb-16">
        <div className="w-64">
          <div className="flex justify-between py-2 border-b border-gray-200">
            <span className="text-gray-600">Subtotal</span>
            <span>${Number(order.totalAmount).toFixed(2)}</span>
          </div>
          <div className="flex justify-between py-2 border-b border-gray-200">
            <span className="text-gray-600">Tax (0%)</span>
            <span>$0.00</span>
          </div>
          <div className="flex justify-between py-3 border-b-2 border-black font-bold text-lg">
            <span>Total</span>
            <span>${Number(order.totalAmount).toFixed(2)}</span>
          </div>
        </div>
      </div>

      {/* Footer */}
      <div className="text-center text-sm text-gray-500 mt-auto pt-8 border-t border-gray-200">
        <p>Thank you for your business.</p>
        <p className="mt-1 text-xs">Generated by Synocre ERP System</p>
      </div>
    </div>
  );
}
